// <auto-generated />
#nullable enable
namespace MUnique.OpenMU.Persistence.Initialization.Properties;

using System.Globalization;
using System.Resources;

/// <summary>Strongly typed ItemOptionNames resources.</summary>
public static class ItemOptionNames
{
    /// <summary>Gets the resource manager.</summary>
    public static ResourceManager ResourceManager { get; } = new("MUnique.OpenMU.Persistence.Initialization.Properties.ItemOptionNames", typeof(ItemOptionNames).Assembly);

    /// <summary>Gets or sets the culture used by the string accessors.</summary>
    public static CultureInfo? Culture { get; set; }

    /// <summary>Gets the localized Level2ndWingOptions name.</summary>
    public static string Level2ndWingOptions => ResourceManager.GetString(nameof(Level2ndWingOptions), Culture)!;

    /// <summary>Gets the localized Level3rdWingOptions name.</summary>
    public static string Level3rdWingOptions => ResourceManager.GetString(nameof(Level3rdWingOptions), Culture)!;

    /// <summary>Gets the localized AgnisAncientSet name.</summary>
    public static string AgnisAncientSet => ResourceManager.GetString(nameof(AgnisAncientSet), Culture)!;

    /// <summary>Gets the localized AncientBonusOfTotalAgility name.</summary>
    public static string AncientBonusOfTotalAgility => ResourceManager.GetString(nameof(AncientBonusOfTotalAgility), Culture)!;

    /// <summary>Gets the localized AncientBonusOfTotalEnergy name.</summary>
    public static string AncientBonusOfTotalEnergy => ResourceManager.GetString(nameof(AncientBonusOfTotalEnergy), Culture)!;

    /// <summary>Gets the localized AncientBonusOfTotalStrength name.</summary>
    public static string AncientBonusOfTotalStrength => ResourceManager.GetString(nameof(AncientBonusOfTotalStrength), Culture)!;

    /// <summary>Gets the localized AncientBonusOfTotalVitality name.</summary>
    public static string AncientBonusOfTotalVitality => ResourceManager.GetString(nameof(AncientBonusOfTotalVitality), Culture)!;

    /// <summary>Gets the localized AnonymousAncientSet name.</summary>
    public static string AnonymousAncientSet => ResourceManager.GetString(nameof(AnonymousAncientSet), Culture)!;

    /// <summary>Gets the localized AnubisAncientSet name.</summary>
    public static string AnubisAncientSet => ResourceManager.GetString(nameof(AnubisAncientSet), Culture)!;

    /// <summary>Gets the localized ApolloAncientSet name.</summary>
    public static string ApolloAncientSet => ResourceManager.GetString(nameof(ApolloAncientSet), Culture)!;

    /// <summary>Gets the localized ArgoAncientSet name.</summary>
    public static string ArgoAncientSet => ResourceManager.GetString(nameof(ArgoAncientSet), Culture)!;

    /// <summary>Gets the localized AruanAncientSet name.</summary>
    public static string AruanAncientSet => ResourceManager.GetString(nameof(AruanAncientSet), Culture)!;

    /// <summary>Gets the localized BarnakeAncientSet name.</summary>
    public static string BarnakeAncientSet => ResourceManager.GetString(nameof(BarnakeAncientSet), Culture)!;

    /// <summary>Gets the localized BaseDamageBonusPhysicalAndWizardryMinAndMaxOption name.</summary>
    public static string BaseDamageBonusPhysicalAndWizardryMinAndMaxOption => ResourceManager.GetString(nameof(BaseDamageBonusPhysicalAndWizardryMinAndMaxOption), Culture)!;

    /// <summary>Gets the localized BaseDefenseOption name.</summary>
    public static string BaseDefenseOption => ResourceManager.GetString(nameof(BaseDefenseOption), Culture)!;

    /// <summary>Gets the localized BerserkerAncientSet name.</summary>
    public static string BerserkerAncientSet => ResourceManager.GetString(nameof(BerserkerAncientSet), Culture)!;

    /// <summary>Gets the localized BroyAncientSet name.</summary>
    public static string BroyAncientSet => ResourceManager.GetString(nameof(BroyAncientSet), Culture)!;

    /// <summary>Gets the localized CapeOfEmperorOptions name.</summary>
    public static string CapeOfEmperorOptions => ResourceManager.GetString(nameof(CapeOfEmperorOptions), Culture)!;

    /// <summary>Gets the localized CapeOfFighterOptions name.</summary>
    public static string CapeOfFighterOptions => ResourceManager.GetString(nameof(CapeOfFighterOptions), Culture)!;

    /// <summary>Gets the localized CapeOfLordOptions name.</summary>
    public static string CapeOfLordOptions => ResourceManager.GetString(nameof(CapeOfLordOptions), Culture)!;

    /// <summary>Gets the localized CapeOfOverruleOptions name.</summary>
    public static string CapeOfOverruleOptions => ResourceManager.GetString(nameof(CapeOfOverruleOptions), Culture)!;

    /// <summary>Gets the localized CetoAncientSet name.</summary>
    public static string CetoAncientSet => ResourceManager.GetString(nameof(CetoAncientSet), Culture)!;

    /// <summary>Gets the localized ChronoAncientSet name.</summary>
    public static string ChronoAncientSet => ResourceManager.GetString(nameof(ChronoAncientSet), Culture)!;

    /// <summary>Gets the localized CloudAncientSet name.</summary>
    public static string CloudAncientSet => ResourceManager.GetString(nameof(CloudAncientSet), Culture)!;

    /// <summary>Gets the localized CompleteSetBonusLevel10 name.</summary>
    public static string CompleteSetBonusLevel10 => ResourceManager.GetString(nameof(CompleteSetBonusLevel10), Culture)!;

    /// <summary>Gets the localized CompleteSetBonusLevel11 name.</summary>
    public static string CompleteSetBonusLevel11 => ResourceManager.GetString(nameof(CompleteSetBonusLevel11), Culture)!;

    /// <summary>Gets the localized CompleteSetBonusLevel12 name.</summary>
    public static string CompleteSetBonusLevel12 => ResourceManager.GetString(nameof(CompleteSetBonusLevel12), Culture)!;

    /// <summary>Gets the localized CompleteSetBonusLevel13 name.</summary>
    public static string CompleteSetBonusLevel13 => ResourceManager.GetString(nameof(CompleteSetBonusLevel13), Culture)!;

    /// <summary>Gets the localized CompleteSetBonusLevel14 name.</summary>
    public static string CompleteSetBonusLevel14 => ResourceManager.GetString(nameof(CompleteSetBonusLevel14), Culture)!;

    /// <summary>Gets the localized CompleteSetBonusLevel15 name.</summary>
    public static string CompleteSetBonusLevel15 => ResourceManager.GetString(nameof(CompleteSetBonusLevel15), Culture)!;

    /// <summary>Gets the localized CompleteSetBonusAnyLevel name.</summary>
    public static string CompleteSetBonusAnyLevel => ResourceManager.GetString(nameof(CompleteSetBonusAnyLevel), Culture)!;

    /// <summary>Gets the localized CurseBaseDamageMinAndMaxOption name.</summary>
    public static string CurseBaseDamageMinAndMaxOption => ResourceManager.GetString(nameof(CurseBaseDamageMinAndMaxOption), Culture)!;

    /// <summary>Gets the localized DarkHorseOptions name.</summary>
    public static string DarkHorseOptions => ResourceManager.GetString(nameof(DarkHorseOptions), Culture)!;

    /// <summary>Gets the localized DefenseRatePvMOption name.</summary>
    public static string DefenseRatePvMOption => ResourceManager.GetString(nameof(DefenseRatePvMOption), Culture)!;

    /// <summary>Gets the localized DinorantOptions name.</summary>
    public static string DinorantOptions => ResourceManager.GetString(nameof(DinorantOptions), Culture)!;

    /// <summary>Gets the localized DrakeAncientSet name.</summary>
    public static string DrakeAncientSet => ResourceManager.GetString(nameof(DrakeAncientSet), Culture)!;

    /// <summary>Gets the localized EliteSkeletonTransformationRing name.</summary>
    public static string EliteSkeletonTransformationRing => ResourceManager.GetString(nameof(EliteSkeletonTransformationRing), Culture)!;

    /// <summary>Gets the localized ElvianAncientSet name.</summary>
    public static string ElvianAncientSet => ResourceManager.GetString(nameof(ElvianAncientSet), Culture)!;

    /// <summary>Gets the localized EnisAncientSet name.</summary>
    public static string EnisAncientSet => ResourceManager.GetString(nameof(EnisAncientSet), Culture)!;

    /// <summary>Gets the localized EpleteAncientSet name.</summary>
    public static string EpleteAncientSet => ResourceManager.GetString(nameof(EpleteAncientSet), Culture)!;

    /// <summary>Gets the localized EvisAncientSet name.</summary>
    public static string EvisAncientSet => ResourceManager.GetString(nameof(EvisAncientSet), Culture)!;

    /// <summary>Gets the localized ExcellentDefenseOptions name.</summary>
    public static string ExcellentDefenseOptions => ResourceManager.GetString(nameof(ExcellentDefenseOptions), Culture)!;

    /// <summary>Gets the localized ExcellentPhysicalAttackOptions name.</summary>
    public static string ExcellentPhysicalAttackOptions => ResourceManager.GetString(nameof(ExcellentPhysicalAttackOptions), Culture)!;

    /// <summary>Gets the localized ExcellentWizardryAttackOptions name.</summary>
    public static string ExcellentWizardryAttackOptions => ResourceManager.GetString(nameof(ExcellentWizardryAttackOptions), Culture)!;

    /// <summary>Gets the localized FaseAncientSet name.</summary>
    public static string FaseAncientSet => ResourceManager.GetString(nameof(FaseAncientSet), Culture)!;

    /// <summary>Gets the localized FenrirOptions name.</summary>
    public static string FenrirOptions => ResourceManager.GetString(nameof(FenrirOptions), Culture)!;

    /// <summary>Gets the localized GaiaAncientSet name.</summary>
    public static string GaiaAncientSet => ResourceManager.GetString(nameof(GaiaAncientSet), Culture)!;

    /// <summary>Gets the localized GaionAncientSet name.</summary>
    public static string GaionAncientSet => ResourceManager.GetString(nameof(GaionAncientSet), Culture)!;

    /// <summary>Gets the localized GarudaAncientSet name.</summary>
    public static string GarudaAncientSet => ResourceManager.GetString(nameof(GarudaAncientSet), Culture)!;

    /// <summary>Gets the localized GuardianOptionArmor name.</summary>
    public static string GuardianOptionArmor => ResourceManager.GetString(nameof(GuardianOptionArmor), Culture)!;

    /// <summary>Gets the localized GuardianOptionBoots name.</summary>
    public static string GuardianOptionBoots => ResourceManager.GetString(nameof(GuardianOptionBoots), Culture)!;

    /// <summary>Gets the localized GuardianOptionGloves name.</summary>
    public static string GuardianOptionGloves => ResourceManager.GetString(nameof(GuardianOptionGloves), Culture)!;

    /// <summary>Gets the localized GuardianOptionHelm name.</summary>
    public static string GuardianOptionHelm => ResourceManager.GetString(nameof(GuardianOptionHelm), Culture)!;

    /// <summary>Gets the localized GuardianOptionPants name.</summary>
    public static string GuardianOptionPants => ResourceManager.GetString(nameof(GuardianOptionPants), Culture)!;

    /// <summary>Gets the localized GuardianOptionWeapon name.</summary>
    public static string GuardianOptionWeapon => ResourceManager.GetString(nameof(GuardianOptionWeapon), Culture)!;

    /// <summary>Gets the localized GywenAncientSet name.</summary>
    public static string GywenAncientSet => ResourceManager.GetString(nameof(GywenAncientSet), Culture)!;

    /// <summary>Gets the localized HarmonyDefenseOptions name.</summary>
    public static string HarmonyDefenseOptions => ResourceManager.GetString(nameof(HarmonyDefenseOptions), Culture)!;

    /// <summary>Gets the localized HarmonyPhysicalAttackOptions name.</summary>
    public static string HarmonyPhysicalAttackOptions => ResourceManager.GetString(nameof(HarmonyPhysicalAttackOptions), Culture)!;

    /// <summary>Gets the localized HarmonyWizardryAttackOptions name.</summary>
    public static string HarmonyWizardryAttackOptions => ResourceManager.GetString(nameof(HarmonyWizardryAttackOptions), Culture)!;

    /// <summary>Gets the localized HealthRecoverForJewelery name.</summary>
    public static string HealthRecoverForJewelery => ResourceManager.GetString(nameof(HealthRecoverForJewelery), Culture)!;

    /// <summary>Gets the localized HerasAncientSet name.</summary>
    public static string HerasAncientSet => ResourceManager.GetString(nameof(HerasAncientSet), Culture)!;

    /// <summary>Gets the localized HyonAncientSet name.</summary>
    public static string HyonAncientSet => ResourceManager.GetString(nameof(HyonAncientSet), Culture)!;

    /// <summary>Gets the localized HyperionAncientSet name.</summary>
    public static string HyperionAncientSet => ResourceManager.GetString(nameof(HyperionAncientSet), Culture)!;

    /// <summary>Gets the localized JeweleryOptionMaximumAbility name.</summary>
    public static string JeweleryOptionMaximumAbility => ResourceManager.GetString(nameof(JeweleryOptionMaximumAbility), Culture)!;

    /// <summary>Gets the localized JeweleryOptionMaximumMana name.</summary>
    public static string JeweleryOptionMaximumMana => ResourceManager.GetString(nameof(JeweleryOptionMaximumMana), Culture)!;

    /// <summary>Gets the localized KantataAncientSet name.</summary>
    public static string KantataAncientSet => ResourceManager.GetString(nameof(KantataAncientSet), Culture)!;

    /// <summary>Gets the localized KarisAncientSet name.</summary>
    public static string KarisAncientSet => ResourceManager.GetString(nameof(KarisAncientSet), Culture)!;

    /// <summary>Gets the localized Luck name.</summary>
    public static string Luck => ResourceManager.GetString(nameof(Luck), Culture)!;

    /// <summary>Gets the localized MinetAncientSet name.</summary>
    public static string MinetAncientSet => ResourceManager.GetString(nameof(MinetAncientSet), Culture)!;

    /// <summary>Gets the localized MistAncientSet name.</summary>
    public static string MistAncientSet => ResourceManager.GetString(nameof(MistAncientSet), Culture)!;

    /// <summary>Gets the localized MurenAncientSet name.</summary>
    public static string MurenAncientSet => ResourceManager.GetString(nameof(MurenAncientSet), Culture)!;

    /// <summary>Gets the localized OdinAncientSet name.</summary>
    public static string OdinAncientSet => ResourceManager.GetString(nameof(OdinAncientSet), Culture)!;

    /// <summary>Gets the localized PhysicalBaseDamageMinAndMaxOption name.</summary>
    public static string PhysicalBaseDamageMinAndMaxOption => ResourceManager.GetString(nameof(PhysicalBaseDamageMinAndMaxOption), Culture)!;

    /// <summary>Gets the localized RaveAncientSet name.</summary>
    public static string RaveAncientSet => ResourceManager.GetString(nameof(RaveAncientSet), Culture)!;

    /// <summary>Gets the localized SemedenAncientSet name.</summary>
    public static string SemedenAncientSet => ResourceManager.GetString(nameof(SemedenAncientSet), Culture)!;

    /// <summary>Gets the localized SkeletonTransformationRing name.</summary>
    public static string SkeletonTransformationRing => ResourceManager.GetString(nameof(SkeletonTransformationRing), Culture)!;

    /// <summary>Gets the localized SocketBonusOptionsArmors name.</summary>
    public static string SocketBonusOptionsArmors => ResourceManager.GetString(nameof(SocketBonusOptionsArmors), Culture)!;

    /// <summary>Gets the localized SocketBonusOptionsPhysical name.</summary>
    public static string SocketBonusOptionsPhysical => ResourceManager.GetString(nameof(SocketBonusOptionsPhysical), Culture)!;

    /// <summary>Gets the localized SocketBonusOptionsWizardry name.</summary>
    public static string SocketBonusOptionsWizardry => ResourceManager.GetString(nameof(SocketBonusOptionsWizardry), Culture)!;

    /// <summary>Gets the localized SocketOptionsEarth name.</summary>
    public static string SocketOptionsEarth => ResourceManager.GetString(nameof(SocketOptionsEarth), Culture)!;

    /// <summary>Gets the localized SocketOptionsFire name.</summary>
    public static string SocketOptionsFire => ResourceManager.GetString(nameof(SocketOptionsFire), Culture)!;

    /// <summary>Gets the localized SocketOptionsIce name.</summary>
    public static string SocketOptionsIce => ResourceManager.GetString(nameof(SocketOptionsIce), Culture)!;

    /// <summary>Gets the localized SocketOptionsLightning name.</summary>
    public static string SocketOptionsLightning => ResourceManager.GetString(nameof(SocketOptionsLightning), Culture)!;

    /// <summary>Gets the localized SocketOptionsWater name.</summary>
    public static string SocketOptionsWater => ResourceManager.GetString(nameof(SocketOptionsWater), Culture)!;

    /// <summary>Gets the localized SocketOptionsWind name.</summary>
    public static string SocketOptionsWind => ResourceManager.GetString(nameof(SocketOptionsWind), Culture)!;

    /// <summary>Gets the localized SylionAncientSet name.</summary>
    public static string SylionAncientSet => ResourceManager.GetString(nameof(SylionAncientSet), Culture)!;

    /// <summary>Gets the localized ViciousAncientSet name.</summary>
    public static string ViciousAncientSet => ResourceManager.GetString(nameof(ViciousAncientSet), Culture)!;

    /// <summary>Gets the localized WarriorAncientSet name.</summary>
    public static string WarriorAncientSet => ResourceManager.GetString(nameof(WarriorAncientSet), Culture)!;

    /// <summary>Gets the localized WingOfDimensionOptions name.</summary>
    public static string WingOfDimensionOptions => ResourceManager.GetString(nameof(WingOfDimensionOptions), Culture)!;

    /// <summary>Gets the localized WingOfEternalOptions name.</summary>
    public static string WingOfEternalOptions => ResourceManager.GetString(nameof(WingOfEternalOptions), Culture)!;

    /// <summary>Gets the localized WingOfIllusionOptions name.</summary>
    public static string WingOfIllusionOptions => ResourceManager.GetString(nameof(WingOfIllusionOptions), Culture)!;

    /// <summary>Gets the localized WingOfRuinOptions name.</summary>
    public static string WingOfRuinOptions => ResourceManager.GetString(nameof(WingOfRuinOptions), Culture)!;

    /// <summary>Gets the localized WingOfStormOptions name.</summary>
    public static string WingOfStormOptions => ResourceManager.GetString(nameof(WingOfStormOptions), Culture)!;

    /// <summary>Gets the localized WingsOfCurseOptions name.</summary>
    public static string WingsOfCurseOptions => ResourceManager.GetString(nameof(WingsOfCurseOptions), Culture)!;

    /// <summary>Gets the localized WingsOfDarknessOptions name.</summary>
    public static string WingsOfDarknessOptions => ResourceManager.GetString(nameof(WingsOfDarknessOptions), Culture)!;

    /// <summary>Gets the localized WingsOfDespairOptions name.</summary>
    public static string WingsOfDespairOptions => ResourceManager.GetString(nameof(WingsOfDespairOptions), Culture)!;

    /// <summary>Gets the localized WingsOfDragonOptions name.</summary>
    public static string WingsOfDragonOptions => ResourceManager.GetString(nameof(WingsOfDragonOptions), Culture)!;

    /// <summary>Gets the localized WingsOfElfOptions name.</summary>
    public static string WingsOfElfOptions => ResourceManager.GetString(nameof(WingsOfElfOptions), Culture)!;

    /// <summary>Gets the localized WingsOfHeavenOptions name.</summary>
    public static string WingsOfHeavenOptions => ResourceManager.GetString(nameof(WingsOfHeavenOptions), Culture)!;

    /// <summary>Gets the localized WingsOfSatanOptions name.</summary>
    public static string WingsOfSatanOptions => ResourceManager.GetString(nameof(WingsOfSatanOptions), Culture)!;

    /// <summary>Gets the localized WingsOfSoulOptions name.</summary>
    public static string WingsOfSoulOptions => ResourceManager.GetString(nameof(WingsOfSoulOptions), Culture)!;

    /// <summary>Gets the localized WingsOfSpiritsOptions name.</summary>
    public static string WingsOfSpiritsOptions => ResourceManager.GetString(nameof(WingsOfSpiritsOptions), Culture)!;

    /// <summary>Gets the localized WizardryBaseDamageMinAndMaxOption name.</summary>
    public static string WizardryBaseDamageMinAndMaxOption => ResourceManager.GetString(nameof(WizardryBaseDamageMinAndMaxOption), Culture)!;
}
