// <auto-generated />
#nullable enable
namespace MUnique.OpenMU.Persistence.Initialization.Properties;

using System.Globalization;
using System.Resources;

/// <summary>Strongly typed ItemOptionTypeNames resources.</summary>
public static class ItemOptionTypeNames
{
    /// <summary>Gets the resource manager.</summary>
    public static ResourceManager ResourceManager { get; } = new("MUnique.OpenMU.Persistence.Initialization.Properties.ItemOptionTypeNames", typeof(ItemOptionTypeNames).Assembly);

    /// <summary>Gets or sets the culture used by the string accessors.</summary>
    public static CultureInfo? Culture { get; set; }

    /// <summary>Gets the localized AncientBonusOption name.</summary>
    public static string AncientBonusOption => ResourceManager.GetString(nameof(AncientBonusOption), Culture)!;

    /// <summary>Gets the localized AncientOption name.</summary>
    public static string AncientOption => ResourceManager.GetString(nameof(AncientOption), Culture)!;

    /// <summary>Gets the localized BlackFenrirOption name.</summary>
    public static string BlackFenrirOption => ResourceManager.GetString(nameof(BlackFenrirOption), Culture)!;

    /// <summary>Gets the localized BlueFenrirOption name.</summary>
    public static string BlueFenrirOption => ResourceManager.GetString(nameof(BlueFenrirOption), Culture)!;

    /// <summary>Gets the localized DarkHorseOption name.</summary>
    public static string DarkHorseOption => ResourceManager.GetString(nameof(DarkHorseOption), Culture)!;

    /// <summary>Gets the localized ExcellentOption name.</summary>
    public static string ExcellentOption => ResourceManager.GetString(nameof(ExcellentOption), Culture)!;

    /// <summary>Gets the localized GoldFenrirOption name.</summary>
    public static string GoldFenrirOption => ResourceManager.GetString(nameof(GoldFenrirOption), Culture)!;

    /// <summary>Gets the localized GuardianOption name.</summary>
    public static string GuardianOption => ResourceManager.GetString(nameof(GuardianOption), Culture)!;

    /// <summary>Gets the localized JewelOfHarmonyOption name.</summary>
    public static string JewelOfHarmonyOption => ResourceManager.GetString(nameof(JewelOfHarmonyOption), Culture)!;

    /// <summary>Gets the localized LuckCriticalDamageChance5 name.</summary>
    public static string LuckCriticalDamageChance5 => ResourceManager.GetString(nameof(LuckCriticalDamageChance5), Culture)!;

    /// <summary>Gets the localized Option name.</summary>
    public static string Option => ResourceManager.GetString(nameof(Option), Culture)!;

    /// <summary>Gets the localized SocketBonusOption name.</summary>
    public static string SocketBonusOption => ResourceManager.GetString(nameof(SocketBonusOption), Culture)!;

    /// <summary>Gets the localized SocketOption name.</summary>
    public static string SocketOption => ResourceManager.GetString(nameof(SocketOption), Culture)!;

    /// <summary>Gets the localized WingOption name.</summary>
    public static string WingOption => ResourceManager.GetString(nameof(WingOption), Culture)!;
}
