// <auto-generated />
#nullable enable
namespace MUnique.OpenMU.Persistence.Initialization.Properties;

using System.Globalization;
using System.Resources;

/// <summary>Strongly typed ItemSetNames resources.</summary>
public static class ItemSetNames
{
    /// <summary>Gets the resource manager.</summary>
    public static ResourceManager ResourceManager { get; } = new("MUnique.OpenMU.Persistence.Initialization.Properties.ItemSetNames", typeof(ItemSetNames).Assembly);

    /// <summary>Gets or sets the culture used by the string accessors.</summary>
    public static CultureInfo? Culture { get; set; }

    /// <summary>Gets the localized Agnis name.</summary>
    public static string Agnis => ResourceManager.GetString(nameof(Agnis), Culture)!;

    /// <summary>Gets the localized Anonymous name.</summary>
    public static string Anonymous => ResourceManager.GetString(nameof(Anonymous), Culture)!;

    /// <summary>Gets the localized Anubis name.</summary>
    public static string Anubis => ResourceManager.GetString(nameof(Anubis), Culture)!;

    /// <summary>Gets the localized Apollo name.</summary>
    public static string Apollo => ResourceManager.GetString(nameof(Apollo), Culture)!;

    /// <summary>Gets the localized Argo name.</summary>
    public static string Argo => ResourceManager.GetString(nameof(Argo), Culture)!;

    /// <summary>Gets the localized Aruan name.</summary>
    public static string Aruan => ResourceManager.GetString(nameof(Aruan), Culture)!;

    /// <summary>Gets the localized Barnake name.</summary>
    public static string Barnake => ResourceManager.GetString(nameof(Barnake), Culture)!;

    /// <summary>Gets the localized Berserker name.</summary>
    public static string Berserker => ResourceManager.GetString(nameof(Berserker), Culture)!;

    /// <summary>Gets the localized Broy name.</summary>
    public static string Broy => ResourceManager.GetString(nameof(Broy), Culture)!;

    /// <summary>Gets the localized Ceto name.</summary>
    public static string Ceto => ResourceManager.GetString(nameof(Ceto), Culture)!;

    /// <summary>Gets the localized Chrono name.</summary>
    public static string Chrono => ResourceManager.GetString(nameof(Chrono), Culture)!;

    /// <summary>Gets the localized Cloud name.</summary>
    public static string Cloud => ResourceManager.GetString(nameof(Cloud), Culture)!;

    /// <summary>Gets the localized Drake name.</summary>
    public static string Drake => ResourceManager.GetString(nameof(Drake), Culture)!;

    /// <summary>Gets the localized Elvian name.</summary>
    public static string Elvian => ResourceManager.GetString(nameof(Elvian), Culture)!;

    /// <summary>Gets the localized Enis name.</summary>
    public static string Enis => ResourceManager.GetString(nameof(Enis), Culture)!;

    /// <summary>Gets the localized Eplete name.</summary>
    public static string Eplete => ResourceManager.GetString(nameof(Eplete), Culture)!;

    /// <summary>Gets the localized Evis name.</summary>
    public static string Evis => ResourceManager.GetString(nameof(Evis), Culture)!;

    /// <summary>Gets the localized Fase name.</summary>
    public static string Fase => ResourceManager.GetString(nameof(Fase), Culture)!;

    /// <summary>Gets the localized Gaia name.</summary>
    public static string Gaia => ResourceManager.GetString(nameof(Gaia), Culture)!;

    /// <summary>Gets the localized Gaion name.</summary>
    public static string Gaion => ResourceManager.GetString(nameof(Gaion), Culture)!;

    /// <summary>Gets the localized Garuda name.</summary>
    public static string Garuda => ResourceManager.GetString(nameof(Garuda), Culture)!;

    /// <summary>Gets the localized Gywen name.</summary>
    public static string Gywen => ResourceManager.GetString(nameof(Gywen), Culture)!;

    /// <summary>Gets the localized Heras name.</summary>
    public static string Heras => ResourceManager.GetString(nameof(Heras), Culture)!;

    /// <summary>Gets the localized Hyon name.</summary>
    public static string Hyon => ResourceManager.GetString(nameof(Hyon), Culture)!;

    /// <summary>Gets the localized Hyperion name.</summary>
    public static string Hyperion => ResourceManager.GetString(nameof(Hyperion), Culture)!;

    /// <summary>Gets the localized Kantata name.</summary>
    public static string Kantata => ResourceManager.GetString(nameof(Kantata), Culture)!;

    /// <summary>Gets the localized Karis name.</summary>
    public static string Karis => ResourceManager.GetString(nameof(Karis), Culture)!;

    /// <summary>Gets the localized Minet name.</summary>
    public static string Minet => ResourceManager.GetString(nameof(Minet), Culture)!;

    /// <summary>Gets the localized Mist name.</summary>
    public static string Mist => ResourceManager.GetString(nameof(Mist), Culture)!;

    /// <summary>Gets the localized Muren name.</summary>
    public static string Muren => ResourceManager.GetString(nameof(Muren), Culture)!;

    /// <summary>Gets the localized Odin name.</summary>
    public static string Odin => ResourceManager.GetString(nameof(Odin), Culture)!;

    /// <summary>Gets the localized Rave name.</summary>
    public static string Rave => ResourceManager.GetString(nameof(Rave), Culture)!;

    /// <summary>Gets the localized Semeden name.</summary>
    public static string Semeden => ResourceManager.GetString(nameof(Semeden), Culture)!;

    /// <summary>Gets the localized Sylion name.</summary>
    public static string Sylion => ResourceManager.GetString(nameof(Sylion), Culture)!;

    /// <summary>Gets the localized Vicious name.</summary>
    public static string Vicious => ResourceManager.GetString(nameof(Vicious), Culture)!;

    /// <summary>Gets the localized Warrior name.</summary>
    public static string Warrior => ResourceManager.GetString(nameof(Warrior), Culture)!;
}
