// <auto-generated />
#nullable enable
namespace MUnique.OpenMU.Persistence.Initialization.Properties;

using System.Globalization;
using System.Resources;

/// <summary>Strongly typed ItemOptionDescriptions resources.</summary>
public static class ItemOptionDescriptions
{
    /// <summary>Gets the resource manager.</summary>
    public static ResourceManager ResourceManager { get; } = new("MUnique.OpenMU.Persistence.Initialization.Properties.ItemOptionDescriptions", typeof(ItemOptionDescriptions).Assembly);

    /// <summary>Gets or sets the culture used by the string accessors.</summary>
    public static CultureInfo? Culture { get; set; }

    /// <summary>Gets the localized ThisOptionIsAddedByTheChaosMachineWithAJewelOfGuardianOnLevel380Items name.</summary>
    public static string ThisOptionIsAddedByTheChaosMachineWithAJewelOfGuardianOnLevel380Items => ResourceManager.GetString(nameof(ThisOptionIsAddedByTheChaosMachineWithAJewelOfGuardianOnLevel380Items), Culture)!;
}
